<a href="https://colab.research.google.com/github/anishraj-38/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
print(np.__version__)

2.0.2


## Creating Arrays

In [4]:
list1 = [1,2,3,45,6]
print(list1)

[1, 2, 3, 45, 6]


In [5]:
arr_list1=np.array(list1)
print(arr_list1)

[ 1  2  3 45  6]


In [6]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [7]:
list2=[[1,2,3],[4,5,6]]
arr_list2=np.array(list2)
print(arr_list2)


[[1 2 3]
 [4 5 6]]


In [8]:
print(arr_list2.ndim)

2


In [10]:
list3 = [[[0,1],[2,3],[8,0]]]
arr_list3=np.array(list3)
print(arr_list3)
print(arr_list3.ndim)

[[[0 1]
  [2 3]
  [8 0]]]
3


In [11]:
list2=[[1,2,3],[4,5,6]]
arr_list2=np.array(list2)
print(arr_list2)


[[1 2 3]
 [4 5 6]]


In [14]:
print("Shape",arr_list2.shape)
print("Size",arr_list2.size)
print("dType",arr_list2.dtype)
print("N-Dimension",arr_list2.ndim)



Shape (2, 3)
Size 6
dType int64
N-Dimension 2


In [19]:
l1=[1,2,3]
l3=[[[1,2],[3,4]]]

arr1=np.array(l1)
arr3=np.array(l3)

print("Shape",arr1.shape)
print("Size",arr1.size)
print("N Dimention",arr1.ndim)
print("Data Type",arr1.dtype)
print("-----------")
print("Shape",arr3.shape)
print("Size",arr3.size)
print("N Dimention",arr3.ndim)
print("Data Type",arr3.dtype)

Shape (3,)
Size 3
N Dimention 1
Data Type int64
-----------
Shape (1, 2, 2)
Size 4
N Dimention 3
Data Type int64


Array Initialization Method

In [21]:
#Zeros Array
zero_arr=np.zeros((2,5))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#One Array
one_arr=np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#Full Array
full_arr=np.full((3,7),8)
print(full_arr)

[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [24]:
#Identity Matrix
id_arr=np.eye(6)
print(id_arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
print(np.empty(2))

[ 5.95550201e-091 -1.22706934e-300]


In [28]:
print(np.arange(1,6,1))

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [7]:
#Random values array
r_arr=np.random.randint(1,67,(3,6))
print(r_arr)

[[25 22 44 28  4 57]
 [ 9 40 40  9 45 25]
 [64  8  2 61 52 30]]


**Slicing in array**

In [10]:
arr1=np.array([1,2,3,45,6,7,8,9])
print(arr1[2:5])
print(arr1[::1])

[ 3 45  6]
[ 1  2  3 45  6  7  8  9]


In [20]:
arr2=np.array([[1,2,9],[5,6,0]])
print(arr2[1])
print(arr2[1:])
print(arr2[1][0:])
print(arr2[:1])

[5 6 0]
[[5 6 0]]
[5 6 0]
[[1 2 9]]


#Array reshaping and flattening

In [24]:
Arr1=np.array([1,2,3,4,5,6])
reshape = Arr1.reshape(3,2)
print(reshape)


[[1 2]
 [3 4]
 [5 6]]


In [25]:
flat=reshape.flatten()
print(flat)

[1 2 3 4 5 6]


**Stacking and Splitting**

In [27]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5 6 7 8 9 0]


Broadcasting
```
# This is formatted as code
```



In [28]:
a=np.array([1,2,3,4,5])
b=np.array([6])
print(a+b)

[ 7  8  9 10 11]


In [29]:
a=np.array([[1,2,3],[23,34,45]])
b=np.array([34,23,12])
print(a+b)

[[35 25 15]
 [57 57 57]]


In [33]:
#SAVE

a=np.array([12,34,45])
print(a)
np.save('anish.npy',a)

[12 34 45]
